### ISSUE TITLE
Bug in bootstrap v4, alpha 3: cannot find 'bootstrap' in node_modules

### ISSUE THREAD

**Issue by philipchmalts** [shakacode/bootstrap-loader#112]
Hey,

Not sure if this is something I am doing wrong, but I have been using this loader for months now and noticed that with the latest patch, my bootstrap folder cannot be resolved anymore. I am using bootstrap 4 alpha 2 but now it doesn't seem to be resolving the folder. When I run debug it goes to 
```
[bootstrap-loader]: Using Bootstrap module: bootstrap. 
```

and then throws this error: 

```
./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
[0] Module build failed: Error: 
[0]       Could not find path to 'bootstrap' module.
[0]       Make sure it's installed in your 'node_modules/' directory.
[0]     
[0]     at Object.module.exports.pitch (/Users/philipchmalts/Documents/Development/if-planning/node_modules/bootstrap-loader/lib/bootstrap.loader.js:90:11)
[0]  @ ./~/bootstrap-loader/loader.js 1:0-44

```

Any help would be much appreciated!

Phil

**Comment by sonyan** [comment]
I have the same problem after upgrading

**Comment by philipchmalts** [comment]
Missed that we had ^4.0.0-alpha.2 and it automatically updated to 3 which came out about 5 hours ago. That being said, this project doesn't work with v3 because it seems bootstrap is missing the /dist/js/npm folder entirely. So roll back to alpha 2 for now until they get that figured out.

**Comment by netskape** [comment]
I'm waiting for update

**Comment by lanocturne** [comment]
Need to support alpha 3

**Comment by dj-hedgehog** [comment]
Had the same problem.
@philipchmalts Can you change the title to "Cannot find bootstrap module for Bootstrap 4 alpha 3" or something alike?

**Comment by justin808** [comment]
I'm seeing the issue and trying to fix this one.

**Comment by justin808** [comment]
https://github.com/twbs/bootstrap/issues/20383

Coming out in alpha v4!

**Comment by jerexyz** [comment]
I have the same problem,Waiting too!!!

**Comment by davecarlson** [comment]
yup, looks like it's been fixed - mdo says it'll be in the alpha-3 patch (expected in the next week )

**Comment by sky-coding** [comment]
Our app is fubar'd in IE on alpha-2 due to https://github.com/twbs/bootstrap/issues/17310, need support  for alpha-3, anxiously awaiting this fix!

**Comment by borysn** [comment]
Downgrading to bootstrap alpha 2 does not resolve the issue for me, I still get a module not found. [repo for reference](https://gitlab.com/borysn/sba2-wip/tree/master/frontend)

**Comment by justin808** [comment]
@borysn Make sure you are not using `npm link`. You might want to specify the location of your .bootstraprc file.

**Comment by borysn** [comment]
@justin808 thanks for the reply. npm link is not being used, at least I don't think so? I didn't set that up anywhere. My .bootstraprc file is picked up fine. Here's a debug trace...

```
 12% building modules 23/114 modules 91 active ...ode_modules/bootstrap-loader/no-op.js[bootstrap-loader]:  bootstrap-loader is using config file at 
/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/.bootstraprc 

[bootstrap-loader]:  Hey, we're in DEBUG mode because you have 
      your config log level set to 'debug'. 

[bootstrap-loader]:  Query from webpack config: *none* 

[bootstrap-loader]:  Using Bootstrap module: bootstrap 

[bootstrap-loader]:  resolveModule error is  Error: Cannot find module 'bootstrap' from '/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/bootstrap-loader/lib/utils'
    at Function.module.exports [as sync] (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/resolve/lib/sync.js:33:11)
    at exports.default (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/bootstrap-loader/lib/utils/resolveModule.js:10:23)
    at Object.module.exports.pitch (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/bootstrap-loader/lib/bootstrap.loader.js:111:54)
    at LOADER_EXECUTION (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/loader-runner/lib/LoaderRunner.js:95:14)
    at runSyncOrAsync (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/loader-runner/lib/LoaderRunner.js:96:4)
    at /home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/loader-runner/lib/LoaderRunner.js:146:3
    at loadLoader (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/loader-runner/lib/LoaderRunner.js:140:2)
    at runLoaders (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/loader-runner/lib/LoaderRunner.js:326:2)
    at NormalModule.doBuild (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/webpack/lib/NormalModule.js:125:2)
    at NormalModule.build (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/webpack/lib/NormalModule.js:173:15)
    at Compilation.buildModule (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/webpack/lib/Compilation.js:127:9)
    at /home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/webpack/lib/Compilation.js:303:10
    at /home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/webpack/lib/NormalModuleFactory.js:63:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/tapable/lib/Tapable.js:123:70)
    at onDoneResolving (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at onDoneResolving (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/webpack/lib/NormalModuleFactory.js:135:6)
    at /home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/webpack/lib/NormalModuleFactory.js:130:7
    at /home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/async/lib/async.js:726:13
    at /home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/async/lib/async.js:236:30)
    at _parallel (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/async/lib/async.js:731:9)
    at /home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/webpack/lib/NormalModuleFactory.js:123:12
    at /home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/async/lib/async.js:726:13
    at /home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/async/lib/async.js:52:16
    at done (/home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/async/lib/async.js:246:17)
    at /home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/async/lib/async.js:44:16
    at /home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/async/lib/async.js:723:17
    at /home/p3pt/dev/java/projects/spring-boot-angular2/master/sba2-wip/frontend/node_modules/async/lib/async.js:167:37 

[bootstrap-loader]:  Bootstrap module location (abs): false 
```

**Comment by justin808** [comment]
@borysn Any luck? Be sure that you specify an exact reference for the version of bootstrap. Don't use the `^` symbol.

**Comment by borysn** [comment]
@justin808 i got it going, answered in another thread. Thank you for the reply though (:
