### ISSUE TITLE
Webpack 2 RC3 & Bootstrap 4 alpha 6

### ISSUE THREAD

**Issue by dfmartin** [shakacode/bootstrap-loader#236]
I am using the above versions of webpack and bootstrap.  I am also using the default bootstrap 4 config file.  I have changed the _animations and _tags to the appropriate _transitions and _badge respectively.  I have also added the '-loader' to the end of each style loader.  The issue I am having now is that when building I get an error that the "Path must be a string.  Received undefined"

```
  at assertPath (path.js:7:11)
    at Object.relative (path.js:1226:5)
    at Object.onRender (/Users/davidmartin/development/healthjournal/node_modules/sass-loader/index.js:282:42)
    at Object.<anonymous> (/Users/davidmartin/development/healthjournal/node_modules/sass-loader/node_modules/async/dist/async.js:2234:31)
    at apply (/Users/davidmartin/development/healthjournal/node_modules/sass-loader/node_modules/async/dist/async.js:20:25)
    at Object.<anonymous> (/Users/davidmartin/development/healthjournal/node_modules/sass-loader/node_modules/async/dist/async.js:56:12)
    at Object.callback (/Users/davidmartin/development/healthjournal/node_modules/sass-loader/node_modules/async/dist/async.js:840:16)
    at options.success (/Users/davidmartin/development/healthjournal/node_modules/node-sass/lib/index.js:300:32)
```

This is for a project that was already using sass-loader and node-sass (two of the modules listed in the stack trace) and all was working.  However, I am a bit new to webpack.  Any guidance would be greatly appreciated.

**Comment by matt328** [comment]
I'm trying to get this working with Webpack 2 also, can you elaborate on where you changed things?  I'm trying to use Bootstrap 3, and the one I am interested in is adding the -loader to the end of each style loader.

**Comment by dfmartin** [comment]
I edited this in the ```.bootstraprc``` file.  Make sure that each loader listed under ```styleloaders:``` has the "-loader" at the end.  This is because webpack 2 no longer makes the "-loader" prefix optional.

**Comment by matt328** [comment]
Yes, found that from tracing the source.  It is working now for me with Bootstrap 3, so, I'm sorry I can't help anymore since your issues are specific to Bootstrap 4.

**Comment by Arturszott** [comment]
@matt328 can you share your exact config?  I try to upgrade everything to webpack 2.2.0 without success. This is what happens to me: 

`Module not found: Error: Can't resolve '[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]./lib/bootstrap.styles.loader.js' in '/Users/arturszott/dev/business-center-frontend/node_modules/bootstrap-loader'`

I guess it's connected to how loaders are handled in new version.

**Comment by justin808** [comment]
Please let me know what your findings are. I'm happy to consider a PR.

**Comment by Arturszott** [comment]
It seems that bootstrap-loader has to be adjusted to new syntax.

**Comment by justin808** [comment]
@Arturszott Any PR? If we change this, how do we handle all the different versions?

**Comment by justin808** [comment]
See release 2.1.0.
