### ISSUE TITLE
Examples do not work on windows

### ISSUE THREAD

**Issue by gazorg** [shakacode/bootstrap-loader#240]
Hi, I tried pulling the 1.3.3. release and running one of the examples. This fails already on npm install. 

npm: v4.1.1 
eslint: v3.31.1 (installed globally as seems required). 

There are a number of missing prerequisites for the demos that seems to be necessary to installed globally. So far I've added eslint

I guess that there are more packages that are required to be installed globally. This is a bit strange for a package, I hoped that all dependencies would be included in package.json. Then I'm a newbie on this kind of development so this might of course be in error. 

```
PS C:\Users\myuser\dev\bootstrap-loader\examples\basic> eslint --version
v3.13.1
PS C:\Users\myuser\dev\bootstrap-loader\examples\basic> npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> bootstrap-loader@1.3.3 prepublish C:\Users\myuser\dev\bootstrap-loader
> npm run prerelease


> bootstrap-loader@1.3.3 prerelease C:\Users\myuser\dev\bootstrap-loader
> npm run lint && npm run clean && npm run build


> bootstrap-loader@1.3.3 lint C:\Users\myuser\dev\bootstrap-loader
> eslint --ext .js .

Cannot find module 'eslint-config-shakacode/base'
Referenced from: C:\Users\myuser\dev\bootstrap-loader\.eslintrc
Error: Cannot find module 'eslint-config-shakacode/base'
Referenced from: C:\Users\myuser\dev\bootstrap-loader\.eslintrc
    at ModuleResolver.resolve (C:\Users\dk\AppData\Roaming\npm\node_modules\eslint\lib\util\module-resolver.js:74:19)
    at resolve (C:\Users\dk\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:478:33)
    at load (C:\Users\dk\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:495:26)
    at configExtends.reduceRight.e (C:\Users\dk\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:391:36
)
    at Array.reduceRight (native)
    at applyExtends (C:\Users\dk\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:362:28)
    at Object.load (C:\Users\dk\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:529:22)
    at loadConfig (C:\Users\dk\AppData\Roaming\npm\node_modules\eslint\lib\config.js:63:33)
    at getLocalConfig (C:\Users\dk\AppData\Roaming\npm\node_modules\eslint\lib\config.js:130:29)
    at Config.getConfig (C:\Users\dk\AppData\Roaming\npm\node_modules\eslint\lib\config.js:259:26)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
" "lint"
npm ERR! node v6.9.2
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! bootstrap-loader@1.3.3 lint: `eslint --ext .js .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap-loader@1.3.3 lint script 'eslint --ext .js .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bootstrap-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint --ext .js .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bootstrap-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bootstrap-loader
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\myuser\dev\bootstrap-loader\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
" "prerelease"
npm ERR! node v6.9.2
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! bootstrap-loader@1.3.3 prerelease: `npm run lint && npm run clean && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap-loader@1.3.3 prerelease script 'npm run lint && npm run clean && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bootstrap-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && npm run clean && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bootstrap-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bootstrap-loader
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\myuser\dev\bootstrap-loader\npm-debug.log

npm ERR! addLocal Could not install C:\Users\myuser\dev\bootstrap-loader
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall"
npm ERR! node v6.9.2
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! bootstrap-loader@1.3.3 prepublish: `npm run prerelease`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap-loader@1.3.3 prepublish script 'npm run prerelease'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bootstrap-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run prerelease
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bootstrap-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bootstrap-loader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\myuser\dev\bootstrap-loader\examples\basic\npm-debug.log
PS C:\Users\myuser\dev\bootstrap-loader\examples\basic>
```

**Comment by gazorg** [comment]
My bad. They do work although to be run from some kind of bash. Neither powershell nor cmd did work, but git bash did.
