### ISSUE TITLE
CheckBootstrapVersion breaks when using npm version 5

### ISSUE THREAD

**Issue by FQ400** [shakacode/bootstrap-loader#306]
When using npm5 the bootstrap-loader fails with the following info.

```
Module build failed: TypeError: Invalid Version: https://registry.npmjs.org/bootstrap/-/bootstrap-4.0.0-alpha.6.tgz
    at new SemVer (/Users/xxx/workspace/inferno-project/node_modules/semver/semver.js:293:11)
    at Function.major (/Users/xxx/workspace/inferno-project/node_modules/semver/semver.js:551:10)
    at exports.default (/Users/xxx/workspace/inferno-project/node_modules/bootstrap-loader/lib/utils/checkBootstrapVersion.js:18:31)
    at Object.module.exports.pitch (/Users/xxx/workspace/inferno-project/node_modules/bootstrap-loader/lib/bootstrap.loader.js:159:65)
 @ ./~/bootstrap-loader/loader.js 2:17-61
 @ ./src/index.jsx
```
**What happens is** the bootstrap-loader checks the version of bootstrap using the `version` field in the `package.json` of the installed package in `node_modules` ([see this file](https://github.com/shakacode/bootstrap-loader/blob/master/src/utils/checkBootstrapVersion.js#L18)). The check itself is done by the package `semver`. `semver`'s major function is used to determine the major version number ([Semver Code](https://github.com/npm/node-semver)).

With npm `4.2.0` the version field of installed packages into `node_modules` contains in my case something like `4.0.0-alpha.6`.

With npm `5.0.0` the version field of installed packages into `node_modules` contains something like `https://registry.npmjs.org/bootstrap/-/bootstrap-4.0.0-alpha.6.tgz`. I guess this comes with the `package-lock.json`.

Should the version be checked if it is an url before hand over to semver?

**Comment by justin808** [comment]
I'm open to a PR that solves this issue and ensures we don't break the current behavior.

**Comment by FQ400** [comment]
Ok. :)

**Comment by FQ400** [comment]
The issue I described above seems to be fixed somewhere in between `npm-5.0.1` and `npm-5.0.3`. 

I was in the code and refactored a bit to prepare the fix ([2 commits](https://github.com/shakacode/bootstrap-loader/compare/master...FQ400:npm5_issue?expand=1)) before I noticed the issue was gone.

@justin808 
The fix is no longer needed, so I close the issue.

**Comment by yar3333** [comment]
I have npm 5.0.3 and issue is still here. I regenerate `package-lock.json` by `npm shrinkwrap` and renaming `shrinkwrap.json` to `package-lock.json`, but problem not gone.
```
ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
Module build failed: TypeError: Invalid Version: http://registry.npmjs.org/bootstrap/-/bootstrap-4.0.0-alpha.6.tgz
    at new SemVer (c:\MyProg\Antifraud\Frontend\node_modules\semver\semver.js:293:11)
    at Function.major (c:\MyProg\Antifraud\Frontend\node_modules\semver\semver.js:551:10)
    at exports.default (c:\MyProg\Antifraud\Frontend\node_modules\bootstrap-loader\lib\utils\checkBootstrapVersion.js:12:31)
    at Object.module.exports.pitch (c:\MyProg\Antifraud\Frontend\node_modules\bootstrap-loader\lib\bootstrap.loader.js:157:65)
 @ ./~/bootstrap-loader/loader.js 1:17-61
 @ ./src/vendor.browser.ts
```

**Comment by jwhitmarsh** [comment]
I'm also seeing this issue with npm version 5.5.1. @yar3333 did you find a work around for this?

**Comment by yar3333** [comment]
@jwhitmarsh Sorry, I don't remember the solution for my case... something like downgrading of boostrap-loader...
