### ISSUE TITLE
Cannot find module error: /~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js

### ISSUE THREAD

**Issue by anandrikka** [shakacode/bootstrap-loader#342]
My application is in production for close to 1 year and I should say there are no changes done to package.json. Suddenly bootstrap-loader stopped working and builds are getting failed.

"bootstrap-loader": "^1.3.3",
"bootstrap-sass": "^3.3.7",

```
./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
Module build failed: Error: Cannot find module 'C:\xxx\scripts\node_modules\bootstrap-sass\package.json\package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function._module2.default._resolveFilename (C:\xxx\scripts\node_modules\require-hacker\babel-transpiled-module
\require hacker.js:423:34)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at exports.default (C:\xxx\scripts\node_modules\bootstrap-loader\lib\utils\checkBootstrapVersion.js:8:20)
    at Object.module.exports.pitch (C:\xxx\scripts\node_modules\bootstrap-loader\lib\bootstrap.loader.js:155:65)
 @ ./~/bootstrap-loader/loader.js 1:17-61

ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
Module build failed: Error: Cannot find module 'C:\xxx\scripts\node_modules\bootstrap-sass\package.json\package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function._module2.default._resolveFilename (C:\xxx\scripts\node_modules\require-hacker\babel-transpiled-module
\require hacker.js:423:34)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at exports.default (C:\xxx\scripts\node_modules\bootstrap-loader\lib\utils\checkBootstrapVersion.js:8:20)
    at Object.module.exports.pitch (C:\xxx\scripts\node_modules\bootstrap-loader\lib\bootstrap.loader.js:155:65)
 @ ./~/bootstrap-loader/loader.js 1:17-61
```

There are no changes to my package.json for more than an year & all of sudden it stopped working.

**Comment by lemonCMS** [comment]
I have the same problem. As of today. I tried removing the node_modules and installing it again. I have tried it with npm and yarn. 

Setting the loglevel to debug shows no useful information.

**Comment by ttma1046** [comment]
take a look at the issue I logged. 
Problem with resolve@1.7.0

**Comment by lemonCMS** [comment]
i saw it after i replied her. so for now i have "fixed" the problem. thx.

**Comment by anandrikka** [comment]
@lemonCMS how did you fixed that

**Comment by lemonCMS** [comment]
@anandrikka i pinned resolve version 1.6.0 as a dependency for now in my own project until this is solved. Hence the quotes.

**Comment by anandrikka** [comment]
@lemonCMS Thank you, that solved issue

**Comment by anandrikka** [comment]
closing issue as #343 fixed it

**Comment by anandrikka** [comment]
closing issue as #343 fixed issue.
