### ISSUE TITLE
Error: Cannot find module './lib/bootstrap.loader?extractStyles!./no-op.js'

### ISSUE THREAD

**Issue by chrisblossom** [shakacode/bootstrap-loader#74]
I am unable to get past the error ```Error: Cannot find module './lib/bootstrap.loader?extractStyles!./no-op.js'``` with my isomorphic/universal app. I am using webpack to compile both the server and client (same loaders used).

Please advise.

Below are my relevant configs:

.bootstraprc
```YAML
---
# Output debugging info
loglevel: debug

# Major version of Bootstrap: 3 or 4
bootstrapVersion: 3

# If Bootstrap version 4 is used - turn on/off flexbox model
useFlexbox: true

# Webpack loaders, order matterse
styleLoaders:
  - style
  - css
  - postcss
  - sass

scripts: false

```

Client webpack config:
```js
{ entry:
   { main:
      [ 'babel-polyfill',
        'bootstrap-loader/extractStyles',
        './src/client.js' ] },
  output:
   { path: '/Users/chris/github/app-frontend/build/public',
     filename: '[name]-[hash].js',
     chunkFilename: '[name]-[chunkhash].js',
     publicPath: '/dist/' },
  target: 'web',
  plugins:
   [ ExtractTextPlugin {
       filename: '[name]-[chunkhash].css',
       options: { allChunks: true },
       id: 1 },
     DedupePlugin {},
     UglifyJsPlugin { options: { compress: { screw_ie8: false, warnings: true } } },
     AggressiveMergingPlugin { options: {} },
     Webpack_isomorphic_tools_plugin {
       options:
        { webpack_assets_file_path: 'build/webpack-assets.json',
          webpack_stats_file_path: 'build/webpack-stats.json',
          assets: {} },
       log:
        Log {
          options: { debug: undefined },
          preamble: '[webpack-isomorphic-tools/plugin]' },
       regular_expressions: {},
       regularExpressions: {} },
     IgnorePlugin { resourceRegExp: /node-fetch/, contextRegExp: undefined },
     ProvidePlugin {
       definitions:
        { 'typeof window': '"object"',
          fetch: 'exports?self.fetch!whatwg-fetch' } },
     DefinePlugin {
       definitions:
        { __CLIENT__: true,
          __SERVER__: false,
          __DEVTOOLS__: false,
          __DEVELOPMENT__: false,
          'process.env.NODE_ENV': '"production"' } },
     OccurrenceOrderPlugin { preferEntry: undefined } ],
  devtool: 'source-map',
  context: '/Users/chris/github/app-frontend',
  progress: true,
  resolve:
   { root: '/Users/chris/github/app-frontend/src',
     modulesDirectories: [ 'node_modules' ],
     extensions: [ '', '.json', '.js', '.jsx' ] },
  module:
   { loaders:
      [ { test: /\.jsx?$/,
          exclude: /node_modules/,
          loaders: [ 'babel?{"presets":["es2015","react","stage-2"],"plugins":["transform-jscript","transform-es3-member-expression-literals","transform-es3-property-literals"],"env":{"production":{"plugins":["react-remove-prop-types","transform-react-constant-elements","transform-react-inline-elements"]},"test":{"plugins":["rewire"]}}}' ] },
        { test: /\.json$/, loader: 'json-loader' },
        { test: /\.scss$/,
          loader: '/Users/chris/github/app-frontend/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!style!css?sourceMap&modules&importLoaders=2&localIdentName=[local]___[hash:base64:5]!postcss!sass?sourceMap&outputStyle=expanded&sourceMap=true&sourceMapContents=true' },
        { test: /\.png$/, loader: 'url-loader?limit=1' } ] },
  postcss: [Function: postcss] }
```

Server webpack config:
```js
{ entry:
   { main:
      [ 'babel-polyfill',
        'bootstrap-loader/extractStyles',
        './src/server.js' ] },
  output:
   { path: '/Users/chris/github/app-frontend/build',
     filename: 'server.js',
     chunkFilename: 'server-[chunkhash].js',
     libraryTarget: 'commonjs2',
     publicPath: '/dist/' },
  devtool: 'source-map',
  target: 'node',
  node:
   { console: false,
     global: false,
     process: false,
     Buffer: false,
     __filename: false,
     __dirname: false },
  externals: [ [Function] ],
  plugins:
   [ BannerPlugin {
       options: { raw: true, entryOnly: false },
       banner: 'require(\'source-map-support\').install();' },
     ExtractTextPlugin {
       filename: 'server-[name].css.ignore',
       options: { allChunks: true },
       id: 2 },
     DefinePlugin {
       definitions:
        { __CLIENT__: false,
          __SERVER__: true,
          __DEVTOOLS__: false,
          __DEVELOPMENT__: false,
          'process.env.NODE_ENV': '"production"' } },
     OccurrenceOrderPlugin { preferEntry: undefined } ],
  context: '/Users/chris/github/app-frontend',
  progress: true,
  resolve:
   { root: '/Users/chris/github/app-frontend/src',
     modulesDirectories: [ 'node_modules' ],
     extensions: [ '', '.json', '.js', '.jsx' ] },
  module:
   { loaders:
      [ { test: /\.jsx?$/,
          exclude: /node_modules/,
          loaders: [ 'babel?{"presets":["es2015","react","stage-2"],"plugins":["transform-jscript","transform-es3-member-expression-literals","transform-es3-property-literals"],"env":{"production":{"plugins":["react-remove-prop-types","transform-react-constant-elements","transform-react-inline-elements"]},"test":{"plugins":["rewire"]}}}' ] },
        { test: /\.json$/, loader: 'json-loader' },
        { test: /\.scss$/,
          loader: '/Users/chris/github/app-frontend/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!style!css?sourceMap&modules&importLoaders=2&localIdentName=[local]___[hash:base64:5]!postcss!sass?sourceMap&outputStyle=expanded&sourceMap=true&sourceMapContents=true' },
        { test: /\.png$/, loader: 'url-loader?limit=1' } ] },
  postcss: [Function: postcss] }
```

```bash
node version: node/4.4.0
```
```bash
chris  ~/github/app-frontend   feature/desktop ●  npm show bootstrap-loader

{ name: 'bootstrap-loader',
  description: 'Boostrap for Webpack',
  'dist-tags': { latest: '1.0.10', 'ver0.1.0-beta1': '0.1.0-beta1' },
  versions:
   [ '0.0.1',
     '0.0.2',
     '0.0.3',
     '0.0.4',
     '0.0.5',
     '0.1.0-beta1',
     '1.0.0-rc',
     '1.0.0',
     '1.0.1',
     '1.0.2',
     '1.0.3',
     '1.0.4',
     '1.0.5',
     '1.0.6',
     '1.0.7',
     '1.0.8',
     '1.0.9',
     '1.0.10' ],
  maintainers:
   [ 'alex.fedoseev <alex.fedoseev@gmail.com>',
     'justin808 <justin.gordon@gmail.com>',
     'shakacode <justin@shakacode.com>' ],
  time:
   { modified: '2016-03-18T09:21:45.275Z',
     created: '2015-11-11T04:18:27.648Z',
     '0.0.1': '2015-11-11T04:18:27.648Z',
     '0.0.2': '2015-11-13T21:42:01.200Z',
     '0.0.3': '2015-11-14T16:34:29.354Z',
     '0.0.4': '2015-11-15T11:51:10.296Z',
     '0.0.5': '2015-11-16T16:34:46.825Z',
     '0.1.0-beta1': '2015-12-07T21:26:12.541Z',
     '1.0.0-rc': '2015-12-11T16:53:04.622Z',
     '1.0.0': '2015-12-23T23:11:25.616Z',
     '1.0.1': '2015-12-23T23:30:08.675Z',
     '1.0.2': '2016-01-04T09:58:33.675Z',
     '1.0.3': '2016-01-06T10:55:18.561Z',
     '1.0.4': '2016-01-16T20:43:36.218Z',
     '1.0.5': '2016-01-16T20:48:54.996Z',
     '1.0.6': '2016-01-24T17:55:14.819Z',
     '1.0.7': '2016-01-26T08:00:22.822Z',
     '1.0.8': '2016-02-08T10:22:57.867Z',
     '1.0.9': '2016-02-29T10:33:27.993Z',
     '1.0.10': '2016-03-18T09:21:45.275Z' },
  homepage: 'https://github.com/shakacode/bootstrap-loader#readme',
  keywords: [ 'bootstrap', 'twitter' ],
  repository:
   { type: 'git',
     url: 'git+https://github.com/shakacode/bootstrap-loader.git' },
  bugs: { url: 'https://github.com/shakacode/bootstrap-loader/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  users: { yatsu: true },
  version: '1.0.10',
  main: 'loader.js',
  scripts:
   { start: 'npm run lint && npm run clean && npm run dev',
     dev: 'babel --watch --out-dir lib src',
     build: 'babel --out-dir lib src',
     lint: 'eslint --ext .js .',
     clean: 'rm -rf lib',
     prerelease: 'npm run lint && npm run clean && npm run build',
     preversion: 'npm run prerelease',
     prepublish: 'npm run prerelease',
     'release:patch': 'scripts/release patch',
     'release:minor': 'scripts/release minor',
     'release:major': 'scripts/release major' },
  authors:
   [ 'Justin Gordon <justin.gordon@gmail.com> (https://github.com/justin808)',
     'Alex Fedoseev <alex.fedoseev@gmail.com> (https://github.com/alexfedoseev)' ],
  peerDependencies:
   { 'css-loader': '*',
     'node-sass': '*',
     'resolve-url-loader': '*',
     'sass-loader': '*',
     'url-loader': '*',
     webpack: '*' },
  dependencies:
   { chalk: '^1.1.1',
     'escape-regexp': '0.0.1',
     'js-yaml': '^3.4.3',
     'loader-utils': '^0.2.11',
     resolve: '^1.1.6',
     semver: '^5.0.3',
     'strip-json-comments': '^1.0.4' },
  devDependencies:
   { babel: '^6.0.15',
     'babel-cli': '^6.1.4',
     'babel-preset-es2015': '^6.1.4',
     eslint: '^1.10.3',
     'eslint-config-airbnb': '^2.0.0' },
  gitHead: '2fadab2ddae2e33abee648a598bcc4c92e91f9e3',
  dist:
   { shasum: '67f112c240eb5d8a7b9d017791798d497d1f2206',
     tarball: 'http://registry.npmjs.org/bootstrap-loader/-/bootstrap-loader-1.0.10.tgz' },
  directories: {} }
```

Debug output:
```bash
[bootstrap-loader]:  Hey, we're in DEBUG mode! Yabba dabba doo!

[bootstrap-loader]:  Context: /Users/chris/github/app-frontend/node_modules/bootstrap-loader

[bootstrap-loader]:  Using Bootstrap version: 3

[bootstrap-loader]:  Using Bootstrap module: bootstrap-sass

[bootstrap-loader]:  Bootstrap module location (abs): /Users/chris/github/app-frontend/node_modules/bootstrap-sass

[bootstrap-loader]:  Bootstrap module location (rel): ../bootstrap-sass

[bootstrap-loader]:  Bootstrap NPM package version: 3.3.6

[bootstrap-loader]:  Query from webpack config: ?extractStyles

[bootstrap-loader]:  Normalized params:
 { bootstrapPath: '/Users/chris/github/app-frontend/node_modules/bootstrap-sass',
  bootstrapRelPath: '../bootstrap-sass',
  bootstrapVersion: 3,
  loglevel: 'debug',
  preBootstrapCustomizations: undefined,
  bootstrapCustomizations: undefined,
  appStyles: undefined,
  useFlexbox: true,
  useCustomIconFontPath: undefined,
  extractStyles: true,
  styleLoaders: [ 'style', 'css', 'postcss', 'sass' ],
  styles: false,
  scripts: false }

[bootstrap-loader]:  Requiring:
```

Full error:
```bash
Error: Cannot find module './lib/bootstrap.loader?extractStyles!./no-op.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/chris/github/app-frontend/node_modules/bootstrap-loader/extractStyles.js:1:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by chrisblossom** [comment]
I am not sure what I did to solve my frontend issue, but I solved the backend issue with adding:

```js
import NodeExternals from 'webpack-node-externals';

const nodeModules = new NodeExternals({
  whitelist: ['bootstrap-loader/extractStyles'],
});

// Webpack server config
...
  entry: {
    main: [
      'babel-polyfill',
      'bootstrap-loader/extractStyles',
      './src/server.js',
    ],
  },
  externals: [nodeModules],
...
```

**Comment by otherjohn** [comment]
I am getting the same error but I am using angular2 (https://github.com/AngularClass/angular2-webpack-starter) and Boostrap 4a

**Comment by goncalojuve** [comment]
otherjohn i have the same error that you have. did you solve the error?

**Comment by daniloprates** [comment]
I'm having the same error. Any clues?

**Comment by davidfurlong** [comment]
relevant https://github.com/shakacode/bootstrap-loader/issues/41
